runtime: nodejs20
env: standard
instance_class: F1

env_variables:
  # Ganti dengan IP Address VM MariaDB Anda jika sudah mendapatkannya
  DB_HOST: "34.101.102.84"
  DB_USER: "root"
  DB_PASSWORD: "KomputasiAwan2026!"
  DB_NAME: "db_2411523013"
  PORT: "8080"
